/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.Placar;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import modelo.Jogador;

/**
 *
 * @author lczaikowski
 */
public class Jogo extends javax.swing.JFrame {

    
    public boolean joga = true;
    public boolean jogb = true;
    public int contpos = 0;
    public int k = 0, i = 0;
    int op;
    private String vitoria, derrota, nome;
    public String linha1, linha2, linha3, coluna1, coluna2, coluna3, diagonal1, diagonal2;
    String[][]posvetor = new String[3][3];
    
    Jogador jogador = new Jogador();
    
    public void recebeJogador(Jogador jogador) throws SQLException, NoSuchAlgorithmException{
        this.jogador = jogador;
        consultaPlacar();
    }
    
    public Jogo() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnreiniciar = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        txtvisor = new javax.swing.JTextField();
        btnsair = new javax.swing.JButton();
        txtvisor_nome = new javax.swing.JTextField();
        txtvisor_vitoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtvisor_derrota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnreiniciar.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        btnreiniciar.setText("Reiniciar");
        btnreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreiniciarActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        txtvisor.setEditable(false);
        txtvisor.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        txtvisor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvisorActionPerformed(evt);
            }
        });

        btnsair.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        txtvisor_nome.setEditable(false);
        txtvisor_nome.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtvisor_nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvisor_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvisor_nomeActionPerformed(evt);
            }
        });

        txtvisor_vitoria.setEditable(false);
        txtvisor_vitoria.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtvisor_vitoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvisor_vitoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvisor_vitoriaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("HISTÓRICO:");

        txtvisor_derrota.setEditable(false);
        txtvisor_derrota.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtvisor_derrota.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Vitórias:");

        jLabel3.setText("Derrotas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvisor_nome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtvisor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtvisor_vitoria, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtvisor_derrota)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(104, 104, 104)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtvisor_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtvisor_vitoria, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtvisor_derrota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtvisor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void verificaJogadordaVez(){
        if(joga && jogb){
            this.op = 1;
            joga = false;
            jogb = true;
            txtvisor.setText("Vez do jogador 2");
        } else if (joga && jogb == false){
            this.op = 1;
            joga = false;
            jogb = true;
            txtvisor.setText("Vez do jogador 2");
        } else {
            this.op = 2;
            joga = true;
            jogb = false;
            txtvisor.setText("Jogador(a) da vez " + this.nome);
        }
    }
    
    private void txtvisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvisorActionPerformed
        //Visor de cima
    }//GEN-LAST:event_txtvisorActionPerformed

    public void limpaPosicao(){
        for(i = 0; i < 3; i++){
            for(k = 0; k < 3; k++){
                posvetor[i][k] = "";
            }
        }
    }
    
    public void DesabilitaBotoes() {
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
    }
    
    public void verificaPos(){
        contpos = 0;
        for(i = 0; i < 3; i++){
            for(k = 0; k < 3; k++){
                if(posvetor[i][k] == "X" | posvetor[i][k] == "O"){
                    contpos += 1;
                }
            }
        }
    }
    
    public void consultaPlacar() throws SQLException, NoSuchAlgorithmException{
        
        Placar placar = new Placar();
        String tratar = placar.vitoria(this.jogador);
        String nomeJogador = placar.mostrarPlacar(this.jogador);
        this.nome = nomeJogador;
        this.vitoria = tratar.substring(0,tratar.indexOf("/"));
        this.derrota = tratar.substring(tratar.indexOf("/")+1);
    }
    
    public void vitoria(){
        linha1 = posvetor[0][0] + posvetor[0][1] + posvetor[0][2];
        linha2 = posvetor[1][0] + posvetor[1][1] + posvetor[1][2];
        linha3 = posvetor[2][0] + posvetor[2][1] + posvetor[2][2];
        
        coluna1 = posvetor[0][0] + posvetor[1][0] + posvetor[2][0];
        coluna2 = posvetor[0][1] + posvetor[1][1] + posvetor[2][1];
        coluna3 = posvetor[0][2] + posvetor[1][2] + posvetor[2][2];
        
        diagonal1 = posvetor[0][0] + posvetor[1][1] + posvetor[2][2];
        diagonal2 = posvetor[0][2] + posvetor[1][1] + posvetor[2][0];
        
        if(linha1.equals("XXX") | linha2.equals("XXX") | linha3.equals("XXX") | coluna1.equals("XXX") | coluna2.equals("XXX") | coluna3.equals("XXX") | diagonal1.equals("XXX") | diagonal2.equals("XXX")) {
           txtvisor.setText("Vencedor(a) " + this.nome);
           txtvisor_nome.setText(this.nome);
           txtvisor_vitoria.setText(this.vitoria);
           txtvisor_derrota.setText(this.derrota);
           
           DesabilitaBotoes();
        } else if(linha1.equals("OOO") | linha2.equals("OOO") | linha3.equals("OOO") | coluna1.equals("OOO") | coluna2.equals("OOO") | coluna3.equals("OOO") | diagonal1.equals("OOO") | diagonal2.equals("OOO")){
            txtvisor.setText("Jogador 2 venceu!!");
            DesabilitaBotoes();
        } else if (contpos == 9) {
            txtvisor.setText("Deu velha!");
        }
    }   
    
    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        //botao 1
        verificaJogadordaVez();
        if(op == 1) {
            btn1.setText("X");
            posvetor[0][0] = "X";
        } else {
            btn1.setText("O");
            posvetor[0][0] = "O";
        }
        
        btn1.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
       //botao 2
        verificaJogadordaVez();
        if(op == 1) {
            btn2.setText("X");
            posvetor[0][1] = "X";
        } else {
            btn2.setText("O");
            posvetor[0][1] = "O";
        }
        
        btn2.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        //botao 3
        verificaJogadordaVez();
        if(op == 1) {
            btn3.setText("X");
            posvetor[0][2] = "X";
        } else {
            btn3.setText("O");
            posvetor[0][2] = "O";
        }
        
        btn3.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        //botao 4
        verificaJogadordaVez();
        if(op == 1) {
            btn4.setText("X");
            posvetor[1][0] = "X";
        } else {
            btn4.setText("O");
            posvetor[1][0] = "O";
        }
        
        btn4.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        //botao 5
        verificaJogadordaVez();
        if(op == 1) {
            btn5.setText("X");
            posvetor[1][1] = "X";
        } else {
            btn5.setText("O");
            posvetor[1][1] = "O";
        }
        
        btn5.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        //botao 6
        verificaJogadordaVez();
        if(op == 1) {
            btn6.setText("X");
            posvetor[1][2] = "X";
        } else {
            btn6.setText("O");
            posvetor[1][2] = "O";
        }
        
        btn6.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        //botao 7
        verificaJogadordaVez();
        if(op == 1) {
            btn7.setText("X");
            posvetor[2][0] = "X";
        } else {
            btn7.setText("O");
            posvetor[2][0] = "O";
        }
        
        btn7.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        //botao 8
        verificaJogadordaVez();
        if(op == 1) {
            btn8.setText("X");
            posvetor[2][1] = "X";
        } else {
            btn8.setText("O");
            posvetor[2][1] = "O";
        }
        
        btn8.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        //botao 9
        verificaJogadordaVez();
        if(op == 1) {
            btn9.setText("X");
            posvetor[2][2] = "X";
        } else {
            btn9.setText("O");
            posvetor[2][2] = "O";
        }
        
        btn9.setEnabled(false);
        verificaPos();
        vitoria();
        
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreiniciarActionPerformed
        // Botao Reiniciar
        btn1.setText("");
        btn1.setEnabled(true);
        btn2.setText("");
        btn2.setEnabled(true);
        btn3.setText("");
        btn3.setEnabled(true);
        btn4.setText("");
        btn4.setEnabled(true);
        btn5.setText("");
        btn5.setEnabled(true);
        btn6.setText("");
        btn6.setEnabled(true);
        btn7.setText("");
        btn7.setEnabled(true);
        btn8.setText("");
        btn8.setEnabled(true);
        btn9.setText("");
        btn9.setEnabled(true);
        limpaPosicao();
        txtvisor.setText("");
        txtvisor_vitoria.setText("");
        txtvisor_derrota.setText("");
        joga = true;
        jogb = true;
    }//GEN-LAST:event_btnreiniciarActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        // Botao sair
         System.exit(0);
    }//GEN-LAST:event_btnsairActionPerformed

    private void txtvisor_vitoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvisor_vitoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvisor_vitoriaActionPerformed

    private void txtvisor_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvisor_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvisor_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnreiniciar;
    private javax.swing.JButton btnsair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtvisor;
    private javax.swing.JTextField txtvisor_derrota;
    private javax.swing.JTextField txtvisor_nome;
    private javax.swing.JTextField txtvisor_vitoria;
    // End of variables declaration//GEN-END:variables
}
